/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.message360.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CreateLetterListsletterInput 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5652582841608016218L;
    private Integer page = 1;
    private Integer pagesize = 10;
    private String lettersid;
    private String dateCreated;
    /** GETTER
     * The page count to retrieve from the total results in the collection. Page indexing starts at 1.
     */
    @JsonGetter("page")
    public Integer getPage ( ) { 
        return this.page;
    }
    
    /** SETTER
     * The page count to retrieve from the total results in the collection. Page indexing starts at 1.
     */
    @JsonSetter("page")
    public void setPage (Integer value) { 
        this.page = value;
        notifyObservers(this.page);
    }
 
    /** GETTER
     * The count of objects to return per page.
     */
    @JsonGetter("pagesize")
    public Integer getPagesize ( ) { 
        return this.pagesize;
    }
    
    /** SETTER
     * The count of objects to return per page.
     */
    @JsonSetter("pagesize")
    public void setPagesize (Integer value) { 
        this.pagesize = value;
        notifyObservers(this.pagesize);
    }
 
    /** GETTER
     * The unique identifier for a letter object.
     */
    @JsonGetter("lettersid")
    public String getLettersid ( ) { 
        return this.lettersid;
    }
    
    /** SETTER
     * The unique identifier for a letter object.
     */
    @JsonSetter("lettersid")
    public void setLettersid (String value) { 
        this.lettersid = value;
        notifyObservers(this.lettersid);
    }
 
    /** GETTER
     * The date the letter was created.
     */
    @JsonGetter("dateCreated")
    public String getDateCreated ( ) { 
        return this.dateCreated;
    }
    
    /** SETTER
     * The date the letter was created.
     */
    @JsonSetter("dateCreated")
    public void setDateCreated (String value) { 
        this.dateCreated = value;
        notifyObservers(this.dateCreated);
    }
 
}
 