/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.message360.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CreateConferencesAddParticipantInput 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5701908543404349246L;
    private String conferenceSid;
    private String participantNumber;
    private Boolean muted;
    private Boolean deaf;
    /** GETTER
     * The unique identifier for a conference object.
     */
    @JsonGetter("ConferenceSid")
    public String getConferenceSid ( ) { 
        return this.conferenceSid;
    }
    
    /** SETTER
     * The unique identifier for a conference object.
     */
    @JsonSetter("ConferenceSid")
    public void setConferenceSid (String value) { 
        this.conferenceSid = value;
        notifyObservers(this.conferenceSid);
    }
 
    /** GETTER
     * The phone number of the participant to be added.
     */
    @JsonGetter("ParticipantNumber")
    public String getParticipantNumber ( ) { 
        return this.participantNumber;
    }
    
    /** SETTER
     * The phone number of the participant to be added.
     */
    @JsonSetter("ParticipantNumber")
    public void setParticipantNumber (String value) { 
        this.participantNumber = value;
        notifyObservers(this.participantNumber);
    }
 
    /** GETTER
     * Specifies if participant should be muted.
     */
    @JsonGetter("Muted")
    public Boolean getMuted ( ) { 
        return this.muted;
    }
    
    /** SETTER
     * Specifies if participant should be muted.
     */
    @JsonSetter("Muted")
    public void setMuted (Boolean value) { 
        this.muted = value;
        notifyObservers(this.muted);
    }
 
    /** GETTER
     * Specifies if the participant should hear audio in the conference.
     */
    @JsonGetter("Deaf")
    public Boolean getDeaf ( ) { 
        return this.deaf;
    }
    
    /** SETTER
     * Specifies if the participant should hear audio in the conference.
     */
    @JsonSetter("Deaf")
    public void setDeaf (Boolean value) { 
        this.deaf = value;
        notifyObservers(this.deaf);
    }
 
}
 