/*
 * YtelAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.message360.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Error 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5229250868756634919L;
    private String code;
    private String message;
    private List<String> moreInfo;
    /** GETTER
     * Error Response Code
     */
    @JsonGetter("Code")
    public String getCode ( ) { 
        return this.code;
    }
    
    /** SETTER
     * Error Response Code
     */
    @JsonSetter("Code")
    public void setCode (String value) { 
        this.code = value;
        notifyObservers(this.code);
    }
 
    /** GETTER
     * Error Response Message
     */
    @JsonGetter("Message")
    public String getMessage ( ) { 
        return this.message;
    }
    
    /** SETTER
     * Error Response Message
     */
    @JsonSetter("Message")
    public void setMessage (String value) { 
        this.message = value;
        notifyObservers(this.message);
    }
 
    /** GETTER
     * Detailed Error Info
     */
    @JsonGetter("MoreInfo")
    public List<String> getMoreInfo ( ) { 
        return this.moreInfo;
    }
    
    /** SETTER
     * Detailed Error Info
     */
    @JsonSetter("MoreInfo")
    public void setMoreInfo (List<String> value) { 
        this.moreInfo = value;
        notifyObservers(this.moreInfo);
    }
 
}
 